{application,comet,
             [{description,"comet"},
              {vsn,"0.1"},
              {modules,[comet,comet_app,comet_client,comet_deps,comet_sup,
                        comet_web]},
              {registered,[]},
              {mod,{comet_app,[]}},
              {env,[]},
              {applications,[kernel,stdlib,crypto]}]}.
