{application,comet,
             [{description,"comet"},
              {vsn,"0.1"},
              {modules,[comet,comet_app,comet_client,comet_deps,comet_route,
                        comet_sup,comet_web,comet_web_test]},
              {registered,[]},
              {mod,{comet_app,[]}},
              {env,[]},
              {applications,[kernel,stdlib,crypto]}]}.
